language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements/base-requirements.txt

script:
  # Basically does nothing
  - python -c "from saltant.client import Client"
